INSERT INTO COUNTRY VALUES (1,'Россия');
INSERT INTO COUNTRY VALUES (2,'Германия');
INSERT INTO COUNTRY VALUES (3,'Польша');
INSERT INTO COUNTRY VALUES (4,'Казахстан');

INSERT INTO CITY VALUES (1,'Tомск');
INSERT INTO CITY VALUES (2,'Абакан');
INSERT INTO CITY VALUES (3,'Магадан');
INSERT INTO CITY VALUES (4,'Уфа');
INSERT INTO CITY VALUES (5,'АСТАНА');

INSERT INTO CITY_ADDRESS VALUES (1,'Проспет Ленина','3/a')
INSERT INTO CITY_ADDRESS VALUES (2,'Первомайская','34/1')

INSERT INTO LOCATION VALUES (1,1,1,2);
INSERT INTO LOCATION VALUES (2,5,2,4);

INSERT INTO MAINTENANCE VALUES(1,'Вулканизация');
INSERT INTO MAINTENANCE VALUES(2,'Перебортовка');
INSERT INTO MAINTENANCE VALUES(3,'Установка жгута');
INSERT INTO MAINTENANCE VALUES(4,'Балансировка');
INSERT INTO MAINTENANCE VALUES(5,'Выравнивание обода');
INSERT INTO MAINTENANCE VALUES(6,'Установка заплаток');
INSERT INTO MAINTENANCE VALUES(7,'Накачка колёс');

INSERT INTO SERVICE_CENTER VALUES (1,'ШинПро');
INSERT INTO SERVICE_CENTER VALUES (2,'Альбатрос');

INSERT INTO SERVICE_CENTER_LOCATION VALUES (1,1);
INSERT INTO SERVICE_CENTER_LOCATION VALUES (2,2);

INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (1,1);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (1,2);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (1,3);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (1,4);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (1,7);

INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (2,1);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (2,2);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (2,3);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (2,4);
INSERT INTO SERVICE_CENTER_MAINTENANCE VALUES (2,7);





